# Generated by Django 5.0.6 on 2024-12-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='leavepolicy',
            unique_together={('company', 'leave_type')},
        ),
    ]
