# Generated by Django 5.0.6 on 2024-12-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_leavepolicy_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
