# Generated by Django 5.0.6 on 2024-12-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_leavepolicy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
